#!/usr/bin/env ruby
# encoding: utf-8

require 'optparse'
require File.join(File.dirname(__FILE__), 'rubyfts')

def parse_args(argv)
  opt = Hash.new
  parser = OptionParser.new

  parser.banner = "Usage: #{$0} [options] [head node]\nDefault head node is localhost.\n"

  opt[:input_file] = $stdin
  parser.on('-i', '--input FILE') do |value|
    opt[:input_file] = File.open(value)
  end

  opt[:output_file] = $stdout
  parser.on('-o', '--output FILE') do |value|
    opt[:output_file] = File.open(value, "w")
  end

  parser.parse!(argv)

  opt[:head_node] = if argv.size == 0
                      "localhost"
                    else
                      argv.shift
                    end

  opt
end

def main(argv)
  opt = parse_args(argv)

  c = FullTextSearch::Competition.new(opt[:head_node],
                                      30001,
                                      opt[:output_file])
  c.run(opt[:input_file], true)
end

if __FILE__ == $0 || File.basename($0) == "ruby-prof"
  main(ARGV.dup)
end
