#!/bin/sh

export BASE_DIR="`dirname $0`"
top_dir=$(readlink -f $BASE_DIR)

if test -z "$FTS_NODE"; then
    FTS_NODE="${top_dir}/src/fts-node"
fi

FTS_NODE_ARGS=
FTS_NODE_WRAPPER=
if test x"$DEBUG" = x"yes"; then
    FTS_NODE_WRAPPER="$top_dir/libtool --mode=execute gdb --args"
elif test x"$CHECK_LEAK" = x"yes" || test x"$CHECK_LEAK_HIGHRES" = x"yes" ; then
    export G_SLICE=always-malloc
    export G_DEBUG=gc-friendly
    VALGRIND_LOG=$(mktemp)
    VALGRIND_HIGHRES=
    FTS_NODE_WRAPPER="$top_dir/libtool --mode=execute valgrind "
    FTS_NODE_WRAPPER="$FTS_NODE_WRAPPER --leak-check=full "

    if test x"$CHECK_LEAK_HIGHRES" = x"yes"; then
	FTS_NODE_WRAPPER="$FTS_NODE_WRAPPER --leak-resolution=high"
    fi
    FTS_NODE_WRAPPER="$FTS_NODE_WRAPPER --log-file=${VALGRIND_LOG} -v"
fi

LC_ALL=C
export LC_ALL
echo $FTS_NODE_WRAPPER $FTS_NODE $FTS_NODE_ARGS "$@" $BASE_DIR
$FTS_NODE_WRAPPER $FTS_NODE $FTS_NODE_ARGS "$@" $BASE_DIR

if test x"$CHECK_LEAK" = x"yes"; then
    PAGER=${PAGER}
    if test -z "${PAGER}"; then
	PAGER="less"
    fi
    $PAGER $VALGRIND_LOG
    rm $VALGRIND_LOG
fi
